In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import pandas as pd

df = pd.read_csv('heart.csv')

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [5]:
df.shape

(1025, 14)

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
df.drop(['oldpeak','slope','ca','thal'],axis=1,inplace=True)
df.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  target
0   52    1   0       125   212    0        1      168      0       0
1   53    1   0       140   203    1        0      155      1       0
2   70    1   0       145   174    0        1      125      1       0
3   61    1   0       148   203    0        1      161      0       0
4   62    0   0       138   294    1        1      106      0       0

In [8]:
 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   target    1025 non-null   int64
dtypes: int64(10)
memory usage: 80.2 KB

In [9]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,1.000000

In [12]:
%pip install pgmpy

Requirement already satisfied: pgmpy in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.1.2)
Requirement already satisfied: huggingface_hub>=0.23 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (1.32.0)
Requirement already satisfied: networkx>=3.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (3.6.1)
Requirement already satisfied: numpy>=2.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (2.4.4)
Requirement already satisfied: scipy>=1.10 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (1.18.1)
Requirement already satisfied: scikit-learn>=1.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (1.9.1)
Requirement already satisfied: pandas>=1.5 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (3.0.2)
Requirement already satisfied: statsmodels>=0.14.5 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (0.15.0)
Requirement already satisfied: tqdm>=4.64 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (4.70.1)
Requirement already satisfied: pyparsing>=3.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (3.3.2)
Requirement already satisfied: joblib>=1.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (1.6.0)
Requirement already satisfied: opt_einsum>=3.3 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (3.4.0)
Requirement already satisfied: scikit-base>=0.12.4 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pgmpy) (1.1.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (4.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (2026.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (0.28.1)
Requirement already satisfied: packaging>=20.9 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (4.15.0)
Requirement already satisfied: anyio in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (4.13.0)
Requirement already satisfied: certifi in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (2025.10.5)
Requirement already satisfied: httpcore==1.* in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.0.9)
Requirement already satisfied: idna in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from joblib>=1.2->pgmpy) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.5->pgmpy) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.5->pgmpy) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pgmpy) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.2->pgmpy) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.2->pgmpy) (3.7.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels>=0.14.5->pgmpy) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels>=0.14.5->pgmpy) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->pgmpy) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->pgmpy) (2.4.1)
Requirement already satisfied: colorama in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm>=4.64->pgmpy) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Asus\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [13]:
from pgmpy.models import DiscreteBayesianNetwork 
from pgmpy.estimators import BayesianEstimator
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'target'],
      dtype='str')

In [14]:
model = DiscreteBayesianNetwork([
    ('age', 'target'),
    ('sex', 'target'),
    ('exang', 'target'),
    ('cp', 'target'),
    ('target', 'restecg'),
    ('target', 'chol')
])

estimator = BayesianEstimator(
    model=model,
    data=df
)

cpds = estimator.get_parameters(
    prior_type="BDeu",
    equivalent_sample_size=10
)

model.add_cpds(*cpds)

print(model.get_cpds('age'))

C:\Users\Asus\AppData\Local\Temp\ipykernel_23748\995728787.py:10: FutureWarning: `pgmpy.estimators.BayesianEstimator` is deprecated and will be removed in v1.3.0. Please use `pgmpy.parameter_estimator.DiscreteBayesianEstimator` instead.
  estimator = BayesianEstimator(

+---------+------------+
| age(29) | 0.00410039 |
+---------+------------+
| age(34) | 0.00603276 |
+---------+------------+
| age(35) | 0.0147284  |
+---------+------------+
| age(37) | 0.00603276 |
+---------+------------+
| age(38) | 0.0118299  |
+---------+------------+
| age(39) | 0.0137622  |
+---------+------------+
| age(40) | 0.0108637  |
+---------+------------+
| age(41) | 0.0311535  |
+---------+------------+
| age(42) | 0.0253564  |
+---------+------------+
| age(43) | 0.0253564  |
+---------+------------+
| age(44) | 0.0350183  |
+---------+------------+
| age(45) | 0.0243902  |
+---------+------------+
| age(46) | 0.0224579  |
+---------+------------+
| age(47) | 0.017627   |
+---------+------------+
| age(48) | 0.0224579  |
+---------+------------+
| age(49) | 0.0166608  |
+---------+------------+
| age(50) | 0.0205255  |
+---------+------------+
| age(51) | 0.0379168  |
+---------+------------+
| age(52) | 0.0417815  |
+---------+------------+
| age(53) | 0.0253564  |
+---------+------------+
| age(54) | 0.0514434  |
+---------+------------+
| age(55) | 0.0292212  |
+---------+------------+
| age(56) | 0.0379168  |
+---------+------------+
| age(57) | 0.0553081  |
+---------+------------+
| age(58) | 0.0659361  |
+---------+------------+
| age(59) | 0.0446801  |
+---------+------------+
| age(60) | 0.0359844  |
+---------+------------+
| age(61) | 0.0301873  |
+---------+------------+
| age(62) | 0.0359844  |
+---------+------------+
| age(63) | 0.0311535  |
+---------+------------+
| age(64) | 0.0330859  |
+---------+------------+
| age(65) | 0.0263226  |
+---------+------------+
| age(66) | 0.0243902  |
+---------+------------+
| age(67) | 0.0301873  |
+---------+------------+
| age(68) | 0.0118299  |
+---------+------------+
| age(69) | 0.00893131 |
+---------+------------+
| age(70) | 0.0137622  |
+---------+------------+
| age(71) | 0.0108637  |
+---------+------------+
| age(74) | 0.00313421 |
+---------+------------+
| age(76) | 0.00313421 |
+---------+------------+
| age(77) | 0.00313421 |
+---------+------------+